@extends('admin.dashboard')

{{-- Dynamic Sidebar: عرض كل الـ sections للصفحة الرئيسية --}}
@section('sidebar')
    @include('components.sidebar.accounts')
    @include('components.sidebar.items')
    @include('components.sidebar.discounts')
    @include('components.sidebar.manufacturing')
    @include('components.sidebar.permissions')
    @include('components.sidebar.crm')
    @include('components.sidebar.sales-invoices')
    @include('components.sidebar.purchases-invoices')
    @include('components.sidebar.inventory-invoices')
    @include('components.sidebar.vouchers')
    @include('components.sidebar.transfers')
    @include('components.sidebar.multi-vouchers')
    @include('components.sidebar.contract-journals')
    @include('components.sidebar.depreciation')
    @include('components.sidebar.journals')
    @include('components.sidebar.projects')
    @include('components.sidebar.departments')
    @include('components.sidebar.settings')
    @include('components.sidebar.rentals')
    @include('components.sidebar.service')
    @include('components.sidebar.shipping')
    @include('components.sidebar.POS')
    @include('components.sidebar.daily_progress')
    @include('components.sidebar.inquiries')
    @include('components.sidebar.checks')
@endsection

@section('content')
    @include('dashboard.index')
@endsection